//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLACommonView.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Consts : global::System.Configuration.ApplicationSettingsBase {
        
        private static Consts defaultInstance = ((Consts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Consts())));
        
        public static Consts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品未注册")]
        public string EPC_WEI_ZHU_CE {
            get {
                return ((string)(this["EPC_WEI_ZHU_CE"]));
            }
            set {
                this["EPC_WEI_ZHU_CE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("主条码和辅条码数量不对应")]
        public string TWO_NUMBER_ERROR {
            get {
                return ((string)(this["TWO_NUMBER_ERROR"]));
            }
            set {
                this["TWO_NUMBER_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未扫描到商品")]
        public string WEI_SAO_DAO_EPC {
            get {
                return ((string)(this["WEI_SAO_DAO_EPC"]));
            }
            set {
                this["WEI_SAO_DAO_EPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("箱号不一致")]
        public string XIANG_MA_BU_YI_ZHI {
            get {
                return ((string)(this["XIANG_MA_BU_YI_ZHI"]));
            }
            set {
                this["XIANG_MA_BU_YI_ZHI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未扫描到箱号")]
        public string WEI_SAO_DAO_XIANG_MA {
            get {
                return ((string)(this["WEI_SAO_DAO_XIANG_MA"]));
            }
            set {
                this["WEI_SAO_DAO_XIANG_MA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("箱号重复使用")]
        public string XIANG_MA_CHONG_FU_SHI_YONG {
            get {
                return ((string)(this["XIANG_MA_CHONG_FU_SHI_YONG"]));
            }
            set {
                this["XIANG_MA_CHONG_FU_SHI_YONG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品已扫描")]
        public string EPC_YI_SAO_MIAO {
            get {
                return ((string)(this["EPC_YI_SAO_MIAO"]));
            }
            set {
                this["EPC_YI_SAO_MIAO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("箱规不符")]
        public string BU_FU_HE_XIANG_GUI {
            get {
                return ((string)(this["BU_FU_HE_XIANG_GUI"]));
            }
            set {
                this["BU_FU_HE_XIANG_GUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("重投")]
        public string CHONG_TOU {
            get {
                return ((string)(this["CHONG_TOU"]));
            }
            set {
                this["CHONG_TOU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正常")]
        public string RIGHT {
            get {
                return ((string)(this["RIGHT"]));
            }
            set {
                this["RIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("多个商品")]
        public string DUO_GE_SHANG_PIN {
            get {
                return ((string)(this["DUO_GE_SHANG_PIN"]));
            }
            set {
                this["DUO_GE_SHANG_PIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("多个品色")]
        public string DUO_GE_PIN_SE {
            get {
                return ((string)(this["DUO_GE_PIN_SE"]));
            }
            set {
                this["DUO_GE_PIN_SE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量大于箱规")]
        public string SHU_LIANG_DA_YU_XIANG_GUI {
            get {
                return ((string)(this["SHU_LIANG_DA_YU_XIANG_GUI"]));
            }
            set {
                this["SHU_LIANG_DA_YU_XIANG_GUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品数量大于10个")]
        public string SHANG_PIN_DA_YU_SHI {
            get {
                return ((string)(this["SHANG_PIN_DA_YU_SHI"]));
            }
            set {
                this["SHANG_PIN_DA_YU_SHI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("品色不符")]
        public string PIN_SE_BU_FU {
            get {
                return ((string)(this["PIN_SE_BU_FU"]));
            }
            set {
                this["PIN_SE_BU_FU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("交接号不一致")]
        public string JIAO_JIE_HAO_BU_YI_ZHI {
            get {
                return ((string)(this["JIAO_JIE_HAO_BU_YI_ZHI"]));
            }
            set {
                this["JIAO_JIE_HAO_BU_YI_ZHI"] = value;
            }
        }
    }
}
