//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLACommonView.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class DataSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataSetting defaultInstance = ((DataSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataSetting())));
        
        public static DataSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.18.10.98")]
        public string DBAddress {
            get {
                return ((string)(this["DBAddress"]));
            }
            set {
                this["DBAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("heilandb")]
        public string DBName {
            get {
                return ((string)(this["DBName"]));
            }
            set {
                this["DBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string DBUser {
            get {
                return ((string)(this["DBUser"]));
            }
            set {
                this["DBUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xindeco.123456")]
        public string DBPassword {
            get {
                return ((string)(this["DBPassword"]));
            }
            set {
                this["DBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFormalEnvironmemt {
            get {
                return ((bool)(this["UseFormalEnvironmemt"]));
            }
            set {
                this["UseFormalEnvironmemt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.18.200.86")]
        public string FormalSAPServerAddress {
            get {
                return ((string)(this["FormalSAPServerAddress"]));
            }
            set {
                this["FormalSAPServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04")]
        public string FormalSystemNum {
            get {
                return ((string)(this["FormalSystemNum"]));
            }
            set {
                this["FormalSystemNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string FormalIdleTimeout {
            get {
                return ((string)(this["FormalIdleTimeout"]));
            }
            set {
                this["FormalIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RFC_RFID01")]
        public string FormalSAPUser {
            get {
                return ((string)(this["FormalSAPUser"]));
            }
            set {
                this["FormalSAPUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xinda01")]
        public string FormalSAPPassword {
            get {
                return ((string)(this["FormalSAPPassword"]));
            }
            set {
                this["FormalSAPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public string FormalClient {
            get {
                return ((string)(this["FormalClient"]));
            }
            set {
                this["FormalClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZH")]
        public string FormalLanguage {
            get {
                return ((string)(this["FormalLanguage"]));
            }
            set {
                this["FormalLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string FormalPeakConnectionsLimit {
            get {
                return ((string)(this["FormalPeakConnectionsLimit"]));
            }
            set {
                this["FormalPeakConnectionsLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string FormalPollSize {
            get {
                return ((string)(this["FormalPollSize"]));
            }
            set {
                this["FormalPollSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.18.200.14")]
        public string TestSAPServerAddress {
            get {
                return ((string)(this["TestSAPServerAddress"]));
            }
            set {
                this["TestSAPServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string TestSystemNum {
            get {
                return ((string)(this["TestSystemNum"]));
            }
            set {
                this["TestSystemNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string TestIdleTimeout {
            get {
                return ((string)(this["TestIdleTimeout"]));
            }
            set {
                this["TestIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("093482")]
        public string TestSAPUser {
            get {
                return ((string)(this["TestSAPUser"]));
            }
            set {
                this["TestSAPUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sunrain")]
        public string TestSAPPassword {
            get {
                return ((string)(this["TestSAPPassword"]));
            }
            set {
                this["TestSAPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string TestClient {
            get {
                return ((string)(this["TestClient"]));
            }
            set {
                this["TestClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh")]
        public string TestLanguage {
            get {
                return ((string)(this["TestLanguage"]));
            }
            set {
                this["TestLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string TestPeakConnectionsLimit {
            get {
                return ((string)(this["TestPeakConnectionsLimit"]));
            }
            set {
                this["TestPeakConnectionsLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string TestPollSize {
            get {
                return ((string)(this["TestPollSize"]));
            }
            set {
                this["TestPollSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.18.10.76")]
        public string TestDBAddress {
            get {
                return ((string)(this["TestDBAddress"]));
            }
            set {
                this["TestDBAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("heilandb")]
        public string TestDBName {
            get {
                return ((string)(this["TestDBName"]));
            }
            set {
                this["TestDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string TestDBUser {
            get {
                return ((string)(this["TestDBUser"]));
            }
            set {
                this["TestDBUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xindeco.123456")]
        public string TestDBPassword {
            get {
                return ((string)(this["TestDBPassword"]));
            }
            set {
                this["TestDBPassword"] = value;
            }
        }
    }
}
